CREATE DATABASE DATABASETASK
USE DATABASETASK
CREATE TABLE BOOKS(ID INT,TITLE VARCHAR(250),YEAR INT,AUTHOR VARCHAR(200));
CREATE TABLE REVIEWERS(ID INT,NAME VARCHAR(200));
CREATE TABLE RATINGS(REVIEWER_ID INT,BOOK_ID INT,RATING INT,RATING_DATE DATE)
DROP TABLE BOOKS
INSERT INTO BOOKS VALUES(101,'A TALE OF TWO CITIES',1859,'CHARLES DICKENS')
						,(102,'THE LORD OF THE RINGS',1955,'J.R.R TOLKIEN')
						,(103,'THE HOBBIT',1937,'')
						,(104,'THE LITTLE PRINCE',1943,'ANTONIE DE SAINT-EXUPERY');

INSERT INTO REVIEWERS VALUES(15201,'JOE MARTINEZ')
						   ,(53202,'ALICE LEWIS')
						   ,(44203,'JOHN SMITH');


INSERT INTO RATINGS VALUES(15201,101,2,GETDATE())
					   ,(15201,101,4,GETDATE()-60)
					   ,(53202,103,4,GETDATE()-45)
					   ,(44203,104,5,GETDATE()-90)

ALTER PROCEDURE GETREVIEWDBOOKS
	@ID INT=1
	AS
SELECT B.TITLE,RT.RATING FROM BOOKS B
JOIN RATINGS RT ON RT.BOOK_ID = B.ID
JOIN REVIEWERS R ON R.ID = RT.REVIEWER_ID
WHERE RT.RATING >= @ID ORDER BY B.TITLE
GO

EXEC GETREVIEWDBOOKS 2